apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: yas-spring-monitor
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: security.istio.io/tlsMode
        operator: Exists
  podMetricsEndpoints:
    - path: /actuator/prometheus
      port: metric
      interval: 15s
