apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-search
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/luc1fe4/yas.git'
    targetRevision: 'v3.0.5'
    path: k8s/charts/search
    helm:
      parameters:
        - name: backend.image.tag
          value: 'v3.0.5'
        - name: backend.image.repository
          value: 'besukem/search'
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
