apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-backoffice-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/luc1fe4/yas.git'
    targetRevision: 'v3.0.2'
    path: k8s/charts/backoffice-ui
    helm:
      parameters:
        - name: ui.image.repository
          value: 'besukem/backoffice'
        - name: ui.image.tag
          value: 'v3.0.2'
        - name: ui.service.nodePort
          value: "30191"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
